### ISSUE TITLE
Can't display images

### ISSUE THREAD

**Issue by neww2** [debanjandhar12/logseq-anki-sync#15]
Thank you so much for creating this great plugin!
I just recently switched from Obsidian (where I already used your Obsidian to Anki Plug-in) and was very happy to find out you made the same for LogSeq too! So first of all many thanks for that! 

In Obsidian to Anki adding photos worked perfectly but in for LogSeq to Anki it doesn't. 

![image](https://user-images.githubusercontent.com/96335629/149093909-991d691d-9e59-4880-a6b7-32d60163fcff.png)

Maybe I did something wrong but I couldn't work it out yet, a documentation for that would be really helpful!

Have a wonderful day! :blush:

**Comment by debanjandhar12** [comment]
This seems like a bug.

- Can you give me the md code of the said block in logseq?

- Also, it would be great if you can give me the generated html output in anki (Go to Browse, and search the block by uuid and then select the note and toggle html editor and ss)
![image](https://user-images.githubusercontent.com/49021233/149095530-56323a1c-c7a8-4545-8e37-d91105dc94d4.png)

- Also, what version of Ankiconnect and Logseq Anki Version are you using?

**Comment by neww2** [comment]
Thanks for your fast reply! 

1. This is the md Code for the mentioned block:

- **11. Definieren Sie den Begriff der Fisher-Information einer Stichprobe.** #card
  id:: 61dc4dc6-cc6d-4a71-a172-f35ba9ffd70c
	- ![image.png](../assets/image_1641826755479_0.png)
	  ![image.png](../assets/image_1641826730315_0.png)
	  ² - zweite Ableitung
	  reminder: _Loglikelihood-Funktion_ zufällige Funktion, die von den konkreten WErten abhängt

2. Here the html output:

![image](https://user-images.githubusercontent.com/96335629/149155978-d6086f0d-f00c-428e-95f5-8f55b21f0ad5.png)

**Comment by busera** [comment]
Hi,
try to convert/change the png-image to a jpg.
I had a similar issue and once I change the image type to .jpg it worked.

Cheers

**Comment by debanjandhar12** [comment]
I initially thought it was an problem with the parser but I guess its not.

This indeed seems to be the same problem as described in #4. However, I cant seem to reproduce it. Can one of you sent me the image file for which the image didn't seem to render in anki?

**Comment by neww2** [comment]
Sorry for my late reply. 
Unfortunately it didn't work with .jpg too. 

Here is the picture in .jpg and .png format.
![Screenshot_20220115_124652](https://user-images.githubusercontent.com/96335629/149622331-a722d9ab-d069-4ff9-8380-00e5eba3fbfe.jpg)

![Screenshot_20220115_124652](https://user-images.githubusercontent.com/96335629/149622328-604184c2-177a-4492-afac-c5d36f3f17d6.png)
9/149622310-3dd4edaa-513f-4634-91a8-64042df3e496.png)

**Comment by debanjandhar12** [comment]
> Sorry for my late reply. Unfortunately it didn't work with .jpg too.
> 
> Here is the picture in .jpg and .png format. ![Screenshot_20220115_124652](https://user-images.githubusercontent.com/96335629/149622363-3e50fb82-f5bf-429c-bf31-fadfd7560bbd.jpg) ![Screenshot_20220115_124652](https://user-images.githubusercontent.com/96335629/149622367-ca7bd433-12c9-4744-aaaf-d4fbfdd9f31f.png)

Thanks. Well, idk how to put it.... I am still unable to reproduce this 0_0. 

- Can you go over to `C:\Users\{WindowsUserName}\AppData\Roaming\Anki2\{AnkiProfileName}\collection.media` and check whether the images have been copied over there? If yes, what is their name?
- What is the path to your logseq graph? For example, mine is `E:\Logeq StudyG`.
- Does any error occur in developer console (Ctrl + Shift + I) in logseq when you try to sync? If yes, can you screenshot it?

**Comment by zvmaz** [comment]
I have the same issue: images are not exported to Anki. 

![image](https://user-images.githubusercontent.com/50499302/164326046-639b9221-b7e5-4c40-9d1c-3495f9adccad.png)

It says "no such file or directory," but the files are indeed there.

![image](https://user-images.githubusercontent.com/50499302/164326238-a9fc2262-12e8-48e6-95b8-c8acc1f7ebbb.png)

**Comment by thiswillbeyourgithub** [comment]
Maybe this is caused because anki cannot access files outside of its own folder?

I don't know if it's actually true but that would not surprise me as anki tries to be at least a bit safe against trojan note types and plugins.

If it's the case, then I think media should be sent via action "storeMediaFile" of [ankiconnect](https://github.com/FooSoft/anki-connect#media-actions)

**Comment by debanjandhar12** [comment]
- > If it's the case, then I think media should be sent via action "storeMediaFile" of [ankiconnect](https://github.com/FooSoft/anki-connect#media-actions)

  The plugin infact uses "storeMediaFile" method of ankiconnect [to be more presise it uses multi to execute multiple storeMediaFile methods].

- Also, anki connect usually give operation not permitted error in case the image file cannot be accessed by anki-connect.

**Comment by zvmaz** [comment]
For me, the problem was that Anki didn't have access to my home directory (installed with Flatpak). 

I solved it by giving Anki access to my home directory (using Flatseal).

**Comment by debanjandhar12** [comment]
> For me, the problem was that Anki didn't have access to my home directory (installed with Flatpak).
> 
> I solved it by giving Anki access to my home directory (using Flatseal).

What error was shown in your case? Was it "File not found" error or "Operation not found" error?

**Comment by zvmaz** [comment]
> What error was shown in your case? Was it "File not found" error or "Operation not found" error?

In Logseq: No such file or directory (I posted a screenshot above). I didn't realize that Anki file access might be the problem until you suggested it in a comment above.

**Comment by zvmaz** [comment]
I reproduced the error in Pop!_OS 21: 
- Install Anki from Flathub
- Download logseq AppImage
- Install all the plugins, make a card with an image
Same exact error: No such file or directory. 

I  originally had the problem with Feodra 36.

**Comment by debanjandhar12** [comment]
There is some significant changes with how assets are handled in v2.8.3. [enhance: lazy asset store](https://github.com/debanjandhar12/logseq-anki-sync/commit/15912715cf6cb7920e1567d9882560e9a17119a3)
The plugin now fetches images from logseq instead of handling the responsibility to anki. Hence, problems with permissions should be resolved.

**Comment by yingzhu146** [comment]
fwiw - I still face the same issue

most recent build,

macOS macbook air M1, logseq. 0.7.6, 
Logseq Anki Sync v3.0.0

markdown

```md
![image.png](../assets/V_2tH451UpEjYaelFQf-uLMh2wAQEFyIPczYJdojdZsH6aYNtqRpJt5tF0tN1gfqJ0jdm6QWOuh83nJ8lsJks-l4tw0MGTqO1gONSdXBUp7wP8W5kUrGQBgSqRBjCQbg.png) with slight angle in wing
```

picture
<img width="999" alt="image" src="https://user-images.githubusercontent.com/59233975/177229693-92ac849e-62d6-4968-8e79-79d8e28c0876.png">
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/59233975/177229701-24a3e10a-7a42-42aa-8f0a-47f4aa27ebc2.png">

making sure file exists

```shell
❯ ls -l ../assets/V_2tH451UpEjYaelFQf-uLMh2wAQEFyIPczYJdojdZsH6aYNtqRpJt5tF0tN1gfqJ0jdm6QWOuh83nJ8lsJks-l4tw0MGTqO1gONSdXBUp7wP8W5kUrGQBgSqRBjCQbg.png
-rwxr-xr-x@ 1 yingzhu  staff  6804 Sep  8  2021 ../assets/V_2tH451UpEjYaelFQf-uLMh2wAQEFyIPczYJdojdZsH6aYNtqRpJt5tF0tN1gfqJ0jdm6QWOuh83nJ8lsJks-l4tw0MGTqO1gONSdXBUp7wP8W5kUrGQBgSqRBjCQbg.png

```

**Comment by vikasmistry** [comment]
I encountered a similar issue with displaying images. Despite the image being present and no error logs, it wouldn't show up. Here's how I resolved it:
1. Navigate to Anki, then select Tools and click on Check Database.
2. If the issue persists, verify if any media files are missing by going to Anki, selecting Tools, and clicking on Check Media.
